import { Router } from 'express';
import auth from './auth';
import career from './career';
import hobby from './hobby';
import helpFeedback from './helpFeedback';
import level from './level';
import user from './user';
import story from './story';
import dashboard from './dashboard';
import appSetting from './appSetting';
import store from './store';
import agency from './agency';
import agencyCommission from './agencyCommission';
import gift from './gift';
import giftType from './giftType';
import roomTheme from './roomTheme';
import live from './live';
import game from './game';
import music from './music';
import family from './family';
import coinPackage from './coinPackage';
import payoutMethod from './payoutMethod';
import payoutRequest from './payoutRequest';
import country from './country';
import reaction from './reaction';
import paymentMethod from './paymentMethod';
import notification from './notification';
import announcement from './announcement';
import banner from './banner';
import call from './call';

export default (router: Router): Router => {
  auth(router);
  career(router);
  hobby(router);
  helpFeedback(router);
  level(router);
  user(router);
  story(router);
  dashboard(router);
  appSetting(router);
  store(router);
  agency(router);
  agencyCommission(router);
  gift(router);
  giftType(router);
  roomTheme(router);
  live(router);
  game(router);
  music(router);
  family(router);
  coinPackage(router);
  payoutMethod(router);
  payoutRequest(router);
  country(router);
  reaction(router);
  paymentMethod(router);
  notification(router);
  announcement(router);
  banner(router);
  call(router);
  return router;
};

